# Generated by Django 5.0.2 on 2024-09-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
