# Generated by Django 5.0.2 on 2024-09-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_parkingspot_spot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/vehicles/'),
        ),
    ]
